language: python

python:
  - "3.6"

before_script:
    - wget https://github.com/michaelgale/fxgeometry/archive/master.zip -O /tmp/fxgeometry.zip
    - unzip /tmp/fxgeometry.zip
    - cd fxgeometry-master
    - python setup.py install
    - cd ..

script:
    - python setup.py install
    - cd tests
    - pytest
