language: python

python:
  - "3.7"

before_script:
    - wget https://github.com/michaelgale/toolbox-py/archive/master.zip -O /tmp/toolbox.zip
    - unzip /tmp/toolbox.zip
    - cd toolbox-py-master
    - python setup.py install
    - cd ..

script:
    - python setup.py install
    - cd tests
    - pytest
